### ISSUE TITLE
suggestion: http://cloudwall.me/etc/json-editor.html

### ISSUE THREAD

**Issue by fiatjaf** [dreftymac/stackoverflow.questions.998832#2]
I don't know where to PR this, so the issue:

http://cloudwall.me/etc/json-editor.html

**Comment by dreftymac** [comment]
Greetings fiatjaf,

For future reference, if you have a stackoverflow account, you can post it directly to the thread if you have sufficient rep.

I have added it to the stackoverflow thread, if that's what is needed here. 

If anything else is needed please feel free to open a new issue. Thanks for the additional info!
